<?php

namespace ContainerCxECF3H;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEzi_CommandChainService extends Ezi_CommandChainBundle_Tests_TestKernelDevDebugContainer
{
    /**
     * Gets the public 'ezi.command_chain' shared service.
     *
     * @return \Ezi\CommandChainBundle\Service\CommandChain
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/CommandChainInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Service/CommandChain.php';

        return $container->services['ezi.command_chain'] = new \Ezi\CommandChainBundle\Service\CommandChain(($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
