chain_commands:
  chains:
    default:
      commands:
        'foo:command': ~
        'bar:command': ~
    test1:
      commands:
        'foo:command': ~
        'bar:command': ~
    test2:
      commands:
        'bar:command': ~
        'foo:command': ~