<?php

namespace ContainerNwmxNBD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandChainCommandService extends Ezi_CommandChainBundle_Tests_KernelTestDebugContainer
{
    /**
     * Gets the private 'Ezi\CommandChainBundle\Command\CommandChainCommand' shared service.
     *
     * @return \Ezi\CommandChainBundle\Command\CommandChainCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CommandChainCommand.php';

        $container->privates['Ezi\\CommandChainBundle\\Command\\CommandChainCommand'] = $instance = new \Ezi\CommandChainBundle\Command\CommandChainCommand();

        $instance->setName('command:chain');
        $instance->setDescription('Console chain command');

        return $instance;
    }
}
