<?php

namespace ContainerNwmxNBD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEzi_CommandChainSubscriberService extends Ezi_CommandChainBundle_Tests_KernelTestDebugContainer
{
    /**
     * Gets the private 'ezi.command_chain_subscriber' shared service.
     *
     * @return \Ezi\CommandChainBundle\EventSubscriber\ConsoleCommandSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventSubscriber/ConsoleCommandSubscriber.php';

        return $container->privates['ezi.command_chain_subscriber'] = new \Ezi\CommandChainBundle\EventSubscriber\ConsoleCommandSubscriber(($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), ($container->services['ezi.command_chain_builder'] ?? $container->load('getEzi_CommandChainBuilderService')), ['chains' => []]);
    }
}
