<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTFldAsA\Ezi_CommandChainBundle_Tests_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTFldAsA/Ezi_CommandChainBundle_Tests_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerTFldAsA.legacy');

    return;
}

if (!\class_exists(Ezi_CommandChainBundle_Tests_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerTFldAsA\Ezi_CommandChainBundle_Tests_KernelTestDebugContainer::class, Ezi_CommandChainBundle_Tests_KernelTestDebugContainer::class, false);
}

return new \ContainerTFldAsA\Ezi_CommandChainBundle_Tests_KernelTestDebugContainer([
    'container.build_hash' => 'TFldAsA',
    'container.build_id' => 'c6dab93b',
    'container.build_time' => 1650638800,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTFldAsA');
