<?php

// This file has been auto-generated by the Symfony Dependency Injection Component
// You can reference it in the "opcache.preload" php.ini setting on PHP >= 7.4 when preloading is desired

use Symfony\Component\DependencyInjection\Dumper\Preloader;

if (in_array(PHP_SAPI, ['cli', 'phpdbg'], true)) {
    return;
}

require dirname(__DIR__, 3).'/vendor/autoload.php';
(require __DIR__.'/Ezi_CommandChainBundle_Tests_TestKernelDevDebugContainer.php')->set(\ContainerCxECF3H\Ezi_CommandChainBundle_Tests_TestKernelDevDebugContainer::class, null);
require __DIR__.'/ContainerCxECF3H/getMonolog_LoggerService.php';
require __DIR__.'/ContainerCxECF3H/getEzi_CommandChainBuilderService.php';
require __DIR__.'/ContainerCxECF3H/getEzi_CommandChainService.php';

$classes = [];
$classes[] = 'Ezi\CommandChainBundle\CommandChainBundle';
$classes[] = 'Symfony\Bundle\MonologBundle\MonologBundle';
$classes[] = 'Ezi\CommandChainBundle\Service\CommandChain';
$classes[] = 'Ezi\CommandChainBundle\Service\ChainBuilder';
$classes[] = 'Symfony\Bridge\Monolog\Logger';
$classes[] = 'Monolog\Handler\NullHandler';
$classes[] = 'Symfony\Component\DependencyInjection\ContainerInterface';

$preloaded = Preloader::preload($classes);
