<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCxECF3H\Ezi_CommandChainBundle_Tests_TestKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCxECF3H/Ezi_CommandChainBundle_Tests_TestKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCxECF3H.legacy');

    return;
}

if (!\class_exists(Ezi_CommandChainBundle_Tests_TestKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCxECF3H\Ezi_CommandChainBundle_Tests_TestKernelDevDebugContainer::class, Ezi_CommandChainBundle_Tests_TestKernelDevDebugContainer::class, false);
}

return new \ContainerCxECF3H\Ezi_CommandChainBundle_Tests_TestKernelDevDebugContainer([
    'container.build_hash' => 'CxECF3H',
    'container.build_id' => 'df19575f',
    'container.build_time' => 1650625494,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCxECF3H');
